= Bases de Datos: Trabajo Práctico
@SebastianPintos <spintos@campus.ungs.edu.ar>; @PierozziLuque <solpierozzi@hotmail.com>; jmcorbera <jmcorbera@gmail.com>;
v1, {docdate}. 	Rondelli, Hernan Daniel y Czemerinski, Hernan (COM-01)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

=== Creación de la Base de Datos 

- Se deberá:
* Crear la respectiva Base de Datos.
* Crear las tablas respetando los nombres de tablas, atributos y tipos de datos especificados.
* Agregar las PK’s y FK’s de todas las tablas, por separado de la creación de las tablas. 
* Permitir al usuario borrar todas las PK’s y FK’s, si así lo desea.

=== Instancia de los datos

- Se deberán cargar 20 clientes y 20 comercios. Todos los clientes tendrán una tarjeta,
excepto dos clientes que tendrán dos tarjetas cada uno. 
- Una tarjeta deberá estar expirada en su fecha de vencimiento.
- La tabla cierre deberá tener los cierres de las tarjetas para todo el año 2020.

=== Stored procedures o triggers

El trabajo práctico deberá incluir los siguientes stored procedures ó triggers:

- Autorización de compra: Deberá recibir los datos de una compra número de tarjeta, código de seguridad, número de comercio y monto y que devuelva true si se autoriza la compra ó false si se rechaza. El procedimiento
deberá validar los siguientes elementos antes de autorizar:

* Que el número de tarjeta sea existente, y que corresponda a alguna tarjeta vigente.
En caso de que no cumpla, se debe cargar un rechazo con el mensaje: tarjeta no
válida ó no vigente.

* Que el código de seguridad sea el correcto. En caso de que no cumpla, se debe
cargar un rechazo con el mensaje: código de seguridad inválido.

* Que el monto total de compras pendientes de pago más la compra a realizar no
supere el límite de compra de la tarjeta. En caso de que no cumpla, se debe cargar
un rechazo con el mensaje: supera límite de tarjeta.

* Que la tarjeta no se encuentre vencida. En caso de que no cumpla, se debe cargar
un rechazo con el mensaje: plazo de vigencia expirado.

* Que la tarjeta no se encuentre suspendida. En caso que no cumpla, se debe cargar
un rechazo con el mensaje la tarjeta se encuentra suspendida.
Si se aprueba la compra, se deberá guardar una fila en la tabla compra, con los datos
de la compra.

- Generación del resumen el trabajo práctico deberá contener la lógica que reciba
como parámetros el número de cliente, y el periodo del año, y que guarde en las
tablas que corresponda los datos del resumen con la siguiente información: nombre
y apellido, dirección, número de tarjeta, periodo del resumen, fecha de vencimiento,
todas las compras del periodo, y total a pagar.

- Alertas a clientes: Se deberá proveer la lógica que genere alertas por posibles fraudes. 
Existe un Call Centre que ante cada alerta generada automáticamente, realiza un llamado telefónico
a el cliente, indicándole la alerta detectada, y verifica si se trató de un fraude ó no. 
Se supone que la detección de alertas se ejecuta
automáticamente con cierta frecuencia. Se pide detectar y almacenar las siguientes alertas:
* Todo rechazo se debe ingresar automáticamente a la tabla de alertas. No puede
haber ninguna demora para ingresar un rechazo en la tabla de alertas, se debe
ingresar en el mismo instante en que se generó el rechazo.
* Si una tarjeta registra dos compras en un lapso menor de un minuto en comercios
distintos ubicados en el mismo código postal.
* Si una tarjeta registra dos compras en un lapso menor de 5 minutos en comercios
con diferentes códigos postales.
* Si una tarjeta registra dos rechazos por exceso de límite en el mismo día, la tarjeta
tiene que ser suspendida preventivamente, y se debe grabar una alerta asociada a
este cambio de estado.
- Se deberá crear una tabla con consumos virtuales para probar el sistema, la misma deberá
contener los atributos: nrotarjeta, codseguridad, nrocomercio, monto. Y se deberá
hacer un procedimiento de testeo, que pida autorización para todos los consumos virtuales.
- Todo el código SQL escrito para este trabajo práctico, deberá poder ejecutarse
desde una aplicación CLI escrita en Go.

=== JSON y Base de datos NoSQL

Se deberá guardar los datos de clientes, tarjetas, comercios, y compras (tres por cada entidad)
en una base de datos NoSQL basada en JSON. Para ello, utilizar la base de datos BoltDB.
Este código, también deberá ejecutarse desde una aplicación CLI escrita en Go.

== Descripción
El programa se organiza en dos carpetas y un archivo escrito en Go (main) que sirve como aplicación CLI:

- Carpeta _sql_:
* Contiene toda la lógica asociada a los ítems: Creación de la base de datos, Instancia de los datos y _Stored procedures_ o _triggers_. Se organiza en los siguientes archivos: 
* consumoTest.go
* datos.go
* sql.go
* storedProcedures.go
* tablas.go
* triggers.go

- Carpeta _no-sql_: 
* Contiene la resolución del ítem _JSON_ y Base de datos _NoSQL_.

Se cambiaron los tipos de datos de: _nrooperacion, nrorechazo, nroresumen_ y _nroalerta_ por _serial_ para facilitar el autoincremento de estos campos.

== Implementación
- Descripción de los métodos del archivo _consumoTest.go_:
* _spTestConsumoRechazo_: Crea una _stored procedure_ que toma como parámetro un motivo de rechazo de tipo _text_. Si el parámetro es _''_ se genera un consumo que será una compra válida. Si el parámetro es _'Tarjeta no válida', 'Código de seguridad inválido', 'Supera límite de tarjeta', 'Plazo de vigencia expirado' o	'La tarjeta se encuentra suspendida'_ se generará un consumo que al ejecutar la función _autorizarcompra_  insertará un rechazo con el motivo que corresponda. En caso de que el parámetro sea distinto a las opciones nombradas, la función retornará un string vacío. En caso contrario, retornará el número de tarjeta de una tarjeta elegida aleatoriamente que cumpla con las características especificadas.
* _spTestConsumoAlerta_: Crea una _stored procedure_ que toma como parámetro un código de alerta de tipo _int_. Si el parámetro es 1, genera 2 consumos válidos aleatorios para una misma tarjeta en comercios distintos ubicados en el mismo código postal. Si el parámetro es 5, genera 2 consumos válidos aleatorios para una misma tarjeta en comercios con diferentes códigos postales. Si el parámetro es 32, genera 2 consumos aleatorios inválidos en los que el monto supera el monto total de la tarjeta. Si el parámetro no es ninguno de los anteriores, retorna un string vacío. En caso contrario, retorna el número de tarjeta de la tarjeta aleatoria elegida que cumple con las características especificadas.
* _consumoTest_ : Crea una _stored procedure_ que toma como parámetro un _motivo_ de tipo _text_. Ejecuta la función _spTestConsumoRechazo_ con el _motivo_ indicado. Si _motivo_='' se trata de un consumo que será válido, entonces corrobora que el número de tarjeta devuelto por la función exista dentro de la tabla _compra_. En caso contrario, corrobora que se haya agregado el rechazo y alerta correspondiente al número de tarjeta devuelto y que el código asociado a la alerta sea 0. Devuelve true si la comprobación fue exitosa, false en caso contrario.
* _alertaTest_ : Crea una _stored procedure_ que toma como parámetro un código de alerta de tipo _int_. Ejecuta la función _spTestConsumoAlerta_ con el código pasado como parámetro. Si el número de tarjeta devuelto por la función es _''_ entonces el código ingresado fue inválido y retorna false. En caso contrario, corrobora que se haya ingresado una alerta asociada al número de tarjeta devuelto por la función con el código pasado como parámetro. Si la comprobación es exitosa, retorna true. En caso contrario, retorna false.
* _correrTest_ : Llama a las funciones _spObtenerDisponible, spTestConsumoRechazo, spTestConsumoAlerta, consumoTest, alertaTest_ y luego ejecuta las stored procedures creadas anteriormente con todos los posibles parámetros válidos.
- Descripción de los métodos del archivo _datos.go_ :
* _cargarDatos()_ : Carga la cantidad de datos especificada en las tablas: _cliente_ , _comercio_ y _tarjeta_. Genera los cierres para el año 2020, llamando a _cargarCierres()._
* _cargarCierres()_ : Ejecuta la función _spGenerarCierres_ que crea una _stored procedured_ que toma como parámetro un año y genera todos los cierres de ese año. Luego, llama a esa _Stored Procedured_ con el año 2020. 
- Descripción de los métodos del archivo _sql.go_ :
*  _DbConnection()_ : Conexión a la base de datos. Invoca a la función _logErr_.
* _logErr(err error)_ : Muestra el error si existe.
* _CrearDB()_ : Creación la base de datos tarjeta.
* _CrearTablas()_ : Creación de las tablas, llamando a la función _crearTablas_.
* _CrearPKyFK()_ : Llama a los métodos _crearPK_ y _crearFK_.
* _EliminarPKyFK()_ : Llama a los métodos _eliminarFK_ y _eliminarPK_.
* _CargarDB()_ : Llama a la función _cargarDatos_.
* _GenerarLogicaConsumo()_ : Crea la lógica del consumo llamando a los siguientes métodos encargados de la creación de _stored procedures_ y _triggers_: _spChequearRechazoLimites, spAgregarRechazo, spAutorizarCompra, spAgregarAlertaRechazo, trAgregarAlerta, spTestearConsumo, trAgregarConsumo, spSeguridadCompras, trSeguridadCompras_.
* _TestearConsumo()_ : Llama a la función _correrTest_.
- Descripción de los métodos del archivo _storedProcedures.go_ :
* _spGenerarCierres()_ : Creación de la _stored procedure_ encargada de generar los cierres del año pasado como parámetro. Recorre las 10 posibles terminaciones de tarjetas y los 12 meses del año y crea los cierres.
* _spGenerarResumen()_ : Crea una _stored procedure_ que toma como parámetros: _nrocliente, año, mes_ y retorna _true_ si se ha podido generar el resumen y _false_ en caso contrario. Para generarlo, se utiliza la terminación de la tarjeta del _cliente_ y se busca el período solicitado con esa terminación en la tabla _cierre_. En caso de poder generar el resumen, marca las compras involucradas como pagadas.
* _spChequearRechazoLimites()_ : Crea una _stored procedure_ que toma como parámetro: nrorechazo. Detecta si la tarjeta registra dos rechazos por exceso de límite en el mismo día. En ese caso, cambia el _estado_ de la _tarjeta_ a _suspendida_ e inserta una nueva _alerta_ con _codalerta_: 32.
* _apObtenerDisponible()_ : Crea una _stored procedure_ que toma como parámetro un número de tarjeta y devuelve lo que resta del monto de la tarjeta. Es decir, el monto total menos las compras aún no pagadas.
* _spAutorizarCompra()_ : Crea una _stored procedure_ con parámetros: _nrotarjeta, codseguridad, nrocomercio_, y _monto_. Devuelve _true_ si la compra fue autorizada y _false_ si fue rechazada.
* _spAgregarRechazo()_ : Crea una _stored procedure_ que toma como parámetros: _nrotarjeta, nrocomercio, fecha_ y _motivo_ e inserta esos valores en la tabla _rechazo_. Invoca a la función _ChequearRechazoLimites(nrorechazo)_. 
* _spTestearConsumo()_ : Crea una _stored procedure_ que comprueba si el nuevo insert realizado en consumo es una compra autorizada o rechazada. Llamando a la _stored procedure_ autorizarcompra. En caso de rechazo se agregará a la tabla de rechazos y alertas. En caso de autorización se agregará en la tabla compra.
* _spAgregarAlertaRechazo()_ : Crea una _stored procedure agregar_alerta_ que agrega una _alerta_ con los valores a insertar en la tabla _rechazo_. Con _codalerta:_ 0. Correspondiente a alertas generadas por rechazo.
* _spSeguridadCompras()_ :  Es la encargada de crear la función del _trigger_ _compras_lapso_tiempo_. Esta función checkea que las compras en un lapso de tiempo para una tarjeta en diferentes comercios estén dentro del requerimiento solicitado. En caso de detectar dos compras con lapso menor a un minuto ubicadas en el mismo código postal, se deberá insertar una _alerta_ con _codalerta_: 1. En caso de detectar dos compras con lapso menor a 5 minutos con diferentes códigos postales se deberá insertar una nueva _alerta_ con _codalerta_: 5.
- Descripción de los métodos del archivo _tablas.go_ :
* _crearTablas()_ : Creación de las tablas _cliente_, _tarjeta_ y _compra_.
* _crearPK()_ : Creación de las PK de cada tabla. 
* _crearFK()_ : Creación de las FK de cada tabla.
* _eliminarPK()_ : Elimina las PK creadas.
* _eliminarFK()_ : Elimina las FK creadas.
- Descripción de los métodos del archivo _triggers.go_ :
* _trAgregarConsumo()_ : Crea un _trigger_ que antes de cada _insert_ en la tabla _consumo_, ejecuta la _stored procedured_: _testear_consumo_. Para corroborar si el consumo será una compra aprobada o rechazada. 
* _trAgregarAlerta()_ : Crea un _trigger_ que antes de cada _insert_ en la tabla _rechazo_, ejecuta la _stored procedured_: _agregar_alerta_. Esto sucede para que se agreguen todas las alertas de rechazo, con código de alerta: 0.
* _trSeguridadCompras()_ : Crea un _trigger_ que antes de cada _insert_ en la tabla _compra_, ejecuta la _stored procedured_: _compras_lapso_tiempo_, para corroborar si se ha generado una alerta de código 1 o de código 5. 

- Descripción de los métodos del archivo _noSQL.go_:
* _CargarDatosNoDB()_: Se conecta a la base de datos y utiliza a las funciones _CargarCliente, CargarTarjeta, CargarComercio_ y _CargarCompra_. Indicando los datos de _cliente, tarjeta, comercio y compra respectivamente_. Respetando el órden y tipo de dato de sus atributos. Carga tres filas de cada tipo.
* _CargarCliente(nrocliente, nombre, apellido, domicilio, teléfono)_: Crea un _cliente_ utilizando el _struct Cliente_, con los parámetros especificados. Utiliza a la función _CreateUpdate_ para escribir en el _bucket_, pasándole como parámetros: la base de datos, _Cliente_ como nombre del _bucket, nrocliente_ perteneciente a _cliente_ como _string_ (clave) y un _marshaling_ de _cliente_ como valor.
* _CargarTarjeta(db, nrotarjeta, nrocliente, validadesde, validahasta, codseguridad, limitecompra, estado)_: Crea una _tarjeta_ utilizando el _struct Tarjeta_, con los parámetros especificados. Utiliza a la función _CreateUpdate_ para escribir en el _bucket_, pasándole como parámetros: la base de datos, _Tarjeta_ como nombre del _bucket_, _nrotarjeta_ perteneciente a _tarjeta_ como _string_ (clave) y un _marshaling_ de _tarjeta_ como valor.
* _CargarComercio(db, nrocomercio, nombre, domicilio, codigopostal, telefono)_: Crea un _comercio_ utilizando el _struct_ _Comercio_, con los parámetros especificados. Utiliza a la función _CreateUpdate_ para escribir en el _bucket_, pasándole como parámetros: la base de datos, _Comercio_ como nombre del _bucket_, _nrocomercio_ perteneciente a _comercio_ como _string_ (clave) y un _marshaling_ de _comercio_ como valor.
* _CargarCompra(db, nrooperacion, nrotarjeta, nrocomercio, fecha, monto, pagado)_: Crea una _compra_ utilizando el _struct Compra_, con los parámetros especificados. Utiliza a la función _CreateUpdate_ para escribir en el _bucket_, pasándole como parámetros: la base de datos, _Compra_ como nombre del _bucket, nrooperacion_ perteneciente a _compra_ como _string_ (clave) y un _marshaling_ de _compra_ como valor.
* _CreateUpdate(db, bucketName, key, value)_: Abre una transacción de escritura, crea el _bucket_ si no existe con el nombre indicado. Escribe los datos _key, value_ especificados en el _bucket_ y luego cierra la transacción.
* _ReadUnique(db, bucketName, key)_: Abre una transacción de lectura con el nombre del _bucket_ pasado como parámetro, y obtiene los datos asociados a la clave especificada.

== Conclusiones

A lo largo del TP se nos presentaron algunas dificultades para interpretar los requerimientos del enunciado, para lo cual debimos realizar consultas a los profesores. Proponiendo un ida y vuelta, simulando una relación de cliente-desarrollador.
Con respecto al desarrollo en sí, además de las diapositivas, tuvimos que leer e investigar bastante la documentación de postgresql para resolver las diferentes funciones lógicas que nos planteaba el enunciado. También se leyó e investigó algunos conceptos básicos de GO para elaborar la aplicación de cliente que corriera los algoritmos desarrollados.
Como conclusión final, podemos decir que como equipo nos vimos en el desafío inusual de trabajar remotamente para elaborar este TP. Para poder lograr el resultado final fue necesario armar buenos canales de comunicación donde debatimos, nos consultamos, asignamos tareas, preparamos consultas a los profesores etc. Consideramos que con esfuerzo y dedicación logramos estar a la altura de las circunstancias, lo que no permitió cumplir con todos los puntos planteados, complementándonos bien, como equipo, a la hora de trabajar.

