= Bases de Datos: Trabajo Práctico
@SebastianPintos <spintos@campus.ungs.edu.ar>; @PierozziLuque <solpierozzi@hotmail.com>; jmcorbera <jmcorbera@gmail.com>;
v1, {docdate}. 	Rondelli, Hernan Daniel y Czemerinski, Hernan (COM-01)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

El texto debe ser breve, conciso, simple, y directo. Se debe incluir
sólo lo relevante que ayude a entender el trabajo práctico.

Se recomiendan oraciones y párrafos cortos.

Por último, no olvidar utilizar signos de puntuación y checkear la
ortografía.

== Introducción
=== Creación de la Base de Datos 
Se deberán crear las tablas respetando los nombres de tablas, atributos y tipos de datos
especificados.
Se deberán agregar las PK’s y FK’s de todas las tablas, por separado de la creación de las
tablas. Además, el usuario deberá tener la posibilidad de borrar todas las PK’s y FK’s, si
lo desea.
=== Instancia de los datos
Se deberán cargar 20 clientes y 20 comercios. Todos los clientes tendrán una tarjeta,
excepto dos clientes que tendrán dos tarjetas cada uno. Una tarjeta deberá estar expirada
en su fecha de vencimiento.
La tabla cierre deberá tener los cierres de las tarjetas para todo el año 2020.
=== Stored procedures o triggers
El trabajo práctico deberá incluir los siguientes stored procedures ó triggers:
* Autorización de compra:  se deberá incluir la lógica que reciba los datos de una
compra—número de tarjeta, código de seguridad, número de comercio y monto y
que devuelva true si se autoriza la compra ó false si se rechaza. El procedimiento
deberá validar los siguientes elementos antes de autorizar:
– Que el número de tarjeta sea existente, y que corresponda a alguna tarjeta vigente.
En caso de que no cumpla, se debe cargar un rechazo con el mensaje ?tarjeta no
válida ó no vigente.
– Que el código de seguridad sea el correcto. En caso de que no cumpla, se debe
cargar un rechazo con el mensaje ?código de seguridad inválido.
– Que el monto total de compras pendientes de pago más la compra a realizar no
supere el límite de compra de la tarjeta. En caso de que no cumpla, se debe cargar
un rechazo con el mensaje ?supera límite de tarjeta.
– Que la tarjeta no se encuentre vencida. En caso de que no cumpla, se debe cargar
un rechazo con el mensaje ?plazo de vigencia expirado.
– Que la tarjeta no se encuentre suspendida. En caso que no cumpla, se debe cargar
un rechazo con el mensaje la tarjeta se encuentra suspendida.
Si se aprueba la compra, se deberá guardar una fila en la tabla compra, con los datos
de la compra.
* Generación del resumen el trabajo práctico deberá contener la lógica que reciba
como parámetros el número de cliente, y el periodo del año, y que guarde en las
tablas que corresponda los datos del resumen con la siguiente información: nombre
y apellido, dirección, número de tarjeta, periodo del resumen, fecha de vencimiento,
todas las compras del periodo, y total a pagar.
* Alertas a clientes: Se deberá proveer la lógica que genere alertas por posibles fraudes. 
Existe un Call Centre que ante cada alerta generada automáticamente, realiza un llamado telefónico
a le cliente, indicándole la alerta detectada, y verifica si se trató de un fraude ó no. 
Se supone que la detección de alertas se ejecuta
automáticamente con cierta frecuencia—e.g. de una vez por minuto. Se pide detectar
y almacenar las siguientes alertas:
– Todo rechazo se debe ingresar automáticamente a la tabla de alertas. No puede
haber ninguna demora para ingresar un rechazo en la tabla de alertas, se debe
ingresar en el mismo instante en que se generó el rechazo.
– Si una tarjeta registra dos compras en un lapso menor de un minuto en comercios
distintos ubicados en el mismo código postal.
– Si una tarjeta registra dos compras en un lapso menor de 5 minutos en comercios
con diferentes códigos postales.
– Si una tarjeta registra dos rechazos por exceso de límite en el mismo día, la tarjeta
tiene que ser suspendida preventivamente, y se debe grabar una alerta asociada a
este cambio de estado.
Se deberá crear una tabla con consumos virtuales para probar el sistema, la misma deberá
contener los atributos: nrotarjeta, codseguridad, nrocomercio, monto. Y se deberá
hacer un procedimiento de testeo, que pida autorización para todos los consumos virtuales.
*Todo el código SQL escrito para este trabajo práctico, deberá poder ejecutarse
desde una aplicación CLI escrita en Go.
=== JSON y Base de datos NoSQL
Por úlimo, para poder comparar el modelo relacional con un modelo no relacional NoSQL,
se pide guardar los datos de clientes, tarjetas, comercios, y compras (tres por cada entidad)
en una base de datos NoSQL basada en JSON. Para ello, utilizar la base de datos BoltDB.
Este código, también deberá ejecutarse desde una aplicación CLI escrita en Go.

== Descripción

En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, las decisiones que se fueron tomando a lo largo
del trabajo práctico, y las cuestiones de diseño que consideren
importantes.

También, se puede incluir una descripción general del programa—cómo
funciona.

== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
breve descripción, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos.

También se puede incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.

